hostname: marshtravel.com
services:
  - name: authentication # Require
    revisionHistoryLimit: 1 # Require
    serviceType: NodePort # Require
    ports: # require at least 1 port
      - name: authport # Require and unique for all
        containerPort: 80 #Require
        protocol: TCP # [TCP, UDP] Require
        # targetPort: 80 # Required, If using service type NodePort or ClusterIP remove targetPort
    replicasCount: 1 # Require if autoscaling.enable is false
    autoscaling: # optional
      enable: false
    podTemplate:
      podAnnotations:
        podAnnotationsA: A
        podAnnotationsB: B
      image:
        name: nginx
        tag: latest
        imagePullPolicy: Always # Default "Always"
      imagePullSecrets: 
        - name: "ghcr-credential" # Name of secret contain credential to pull secret image
    ingress:
      path:
      portNumber: 80
  - name: otherservice # Require
    revisionHistoryLimit: 1 # Require
    serviceType: NodePort # Require
    ports:
      - name: otherserviceport # Require
        containerPort: 80 #Require
        protocol: TCP # [TCP, UDP] Require
        # targetPort: 9090
      - name: otherotherport # Require
        containerPort: 90 #Require
        protocol: TCP # [TCP, UDP] Require
        # targetPort: 1010
    replicasCount: 1 # Require if autoscaling.enable is false
    autoscaling: # optional
      enable: false
    podTemplate:
      podAnnotations:  # optional
        podAnnotationsA: A
        podAnnotationsB: B
      image:
        name: nginx
        tag: latest
        imagePullPolicy: Always # Default "Always"
        # imagePullSecrets: 
        # - name: "ghcr-credential"
    ingress:
      path: # default: /api/{{ services.name }}
      portNumber: 80 # required
  # - name: serviceA
  #   revisionHistoryLimit: 1
  #   ports:
  #     - name: serviceAPort
  #       containerPort: 90
  #       protocol: TCP
        