{{- range $service := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}-deployment
  labels:
    marshTravel.serviceName: {{ $service.name }}
spec:
  {{- if not $service.autoscaling.enabled }}
  replicas: {{ default 1 $service.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ $service.revisionHistoryLimit }}
  selector:
    matchLabels:
      marshTravel.serviceName: {{ $service.name }}
  {{- with $service.podTemplate }}
  template:
    metadata:
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        marshTravel.serviceName: {{ $service.name }}
        {{- with .podLabels }}
        {{- . | nindent 8}}
        {{- end }}
    spec:
      {{- with .image.imagePullSecrets }}
      imagePullSecrets: {{ . }}
      {{- end }}
      containers:
        - name: {{ $service.name | lower | trunc 13}}-container
          image: "{{ .image.name }}:{{ .image.tag }}"
          imagePullPolicy: {{ default "Always" .image.pullPolicy }}
          ports:
            {{- range $port := $service.ports }}
            - containerPort: {{ $port.containerPort }}
              name: {{ $port.name | trunc 15 | lower}}
              protocol: {{ $port.protocol }}
            {{- end }}
          {{- with .image.command }}
          command: {{ . }}
          {{- end }}
  {{- end }}
---
{{- end }}