apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bitnews-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - bitnews.world
    secretName: secret-tls
  rules:
  - host: bitnews.world
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bitnews-chart-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ include "bitnews-chart.fullname" . }}
            port:
              number: 8080
      - path: /swagger
        pathType: Prefix
        backend:
          service:
            name: {{ include "bitnews-chart.fullname" . }}
            port:
              number: 8080
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: {{ include "bitnews-chart.fullname" . }}
            port:
              number: 8080
      - path: /websocket
        pathType: Prefix
        backend:
          service:
            name: bitnews-chart-redis-consumer
            port:
              number: 4000
