apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marshtravel-services-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      {{- range $service := .Values.services }}
      {{- $pathName := printf "/api/%s" $service.name -}}
      {{- $serviceName := $service.name }}
      {{- with $service.ingress }}
      - path: {{ default $pathName .path | quote }}
        pathType: Prefix
        backend:
          service:
            name: {{ $serviceName | quote }}
            port:
              number: {{ .portNumber }}
      {{- end }}
      {{- end }}