{{- range $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  labels:
    marshTravel.serviceName: {{ $service.name }}
spec:
  type: {{ $service.serviceType }}
  ports:
    {{- range $port := $service.ports }}
    - port: {{ $port.containerPort }}
      name: {{ $port.name | lower | trunc 15 }}
      protocol: {{ $port.protocol }}
      targetPort: {{ $port.targetPort }}
    {{- end }}
  selector:
      marshTravel.serviceName: {{ $service.name | snakecase | lower | replace "_" "-"}}
---
{{- end }}