apiVersion: v1
kind: Service
metadata:
  name: {{ include "MarshTravel.name" }}
  labels:
    {{- include "MarshTravel.labels" . | nindent 4 -}}
    {{- if .extendLabels }}
    {{ .extendLabels }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .sourcePort }}
      protocol: {{ default "TCP" .portProtocol -}}
      name: {{ default "http" .portName -}}
  selector:
      bitnews.app: backend